remake: clean build
	echo "done"

build:
	rm -rf js-platform components css-platform fonts
	cp -r ../../html/js ./js-platform
	cp -r ../../html/components ./components
	cp -r ../../html/fonts ./fonts
	cp -r ../../html/css ./css-platform
	touch build

clean:
	rm -rf js-platform components css-platform fonts
	rm -rf build
