"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['run.py']
DATA_FILES = [
 '4store',
 'COPYING',
 'data',
 'html',
 'lib-ext',
 'libs',
 'README.md',
 'requirements.txt',
 'run_app.sh',
 'run_ws.sh',
 'rww',
 'scripts',
 'setup_env.sh',
 'tests',
 'webbox.json.default',
 'webbox.icns',
 'wsupdate',
 ]

OPTIONS = {
    'iconfile': 'webbox.icns',
    'argv_emulation': True,
    'includes': # all external modules, taken from generate_includes.py
        ['cStringIO', 'traceback', 'getpass', 'twisted.web.server', 'webbox', 'shutil', 'hashlib', 'lxml.builder', 'lxml', 'uuid', 'webboxhandler', 'websocketclient', 'urllib', 're', 'json', 'rdflib', 'fourstore', 'time', 'sqlite3', 'twisted.web.wsgi', 'rdflib.plugin', 'httputils', 'subscriptions', 'journal', 'diskstore', 'rdflib.serializer', 'urllib2', 'sys', 'cElementTree', 'webbrowser', 'sparqlresults', 'twisted.internet.defer', 'os.path', 'ConfigParser', 'httplib', 'logging', 'rdflib.plugins.serializers.jsonld', 'twisted.web.static', 'twisted.web.util', 'sparqlparse', 'mimeparse', 'pkg_resources', 'urlparse', 'autobahn.websocket', 'setuptools', 'rdflib.graph', 'twisted.web', 'os', 'twisted.internet', 'OpenSSL', 'xml.etree', 'lxml._elementpath']
    }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
