description_lines
	= d:description_line ds:description_lines
			{ return [d].concat(ds); }
	/ d:description_line
			{ return [d]; }

description_line
	= __ $ d:comment
			{ return d; }

comment
	= c:[^\n\r]*
			{ return c.join(''); }

$
	= _ "///" _


_$_ = __ $ __ _$_
	/ __ $ __
	/ __

_
	= [ \t]*
			{ return ''; }

__
	= [ \t\r\n]*
			{ return ''; }


name
	= n:[^ \t\-\n\r\:]+
			{ return n.join(''); }
