tinyMCE.addI18n('nl.ribbon',{
    underline_desc:"Onderstrepen (Ctrl+U)",
    italic_desc:"Cursief (Ctrl+I)",
    bold_desc:"Vet (Ctrl+B)",
    dd:"Definitiebeschrijving",
    dt:"Definitieterm",
    samp:"Codevoorbeeld",
    code:"Code",
    blockquote:"Citaat",
    h6:"Kop 6",
    h5:"Kop 5",
    h4:"Kop 4",
    h3:"Kop 3",
    h2:"Kop 2",
    h1:"Kop 1",
    pre:"Vaste opmaak",
    address:"Adres",
    div:"Div",
    paragraph:"Alinea",
    block:"Opmaak",
    fontdefault:"Lettertype",
    font_size:"Tekengrootte",
    style_select:"Stijlen",
    more_colors:"Meer kleuren",
    toolbar_focus:"Spring naar werkbalk - Alt+Q, Spring naar tekst - Alt-Z, Spring naar elementpad - Alt-X",
    newdocument:"Weet u zeker dat u alle inhoud wilt wissen?",
    path:"Pad",
    clipboard_msg:"Kopi\u00ebren/knippen/plakken is niet beschikbaar in Mozilla en Firefox.\\nWilt u meer informatie over deze beperking?",
    blockquote_desc:"Citaat",
    help_desc:"Help",
    newdocument_desc:"Nieuw document",
    image_props_desc:"Afbeeldingseigenschappen",
    paste_desc:"Plakken",
    copy_desc:"Kopi\u00ebren",
    cut_desc:"Knippen",
    anchor_desc:"Anker invoegen/bewerken",
    visualaid_desc:"Hulplijnen weergeven",
    charmap_desc:"Symbool invoegen",
    backcolor_desc:"Tekstmarkeringskleur",
    forecolor_desc:"Tekstkleur",
    custom1_desc:"Uw eigen beschrijving hier",
    removeformat_desc:"Opmaak verwijderen",
    hr_desc:"Scheidingslijn invoegen",
    sup_desc:"Superscript",
    sub_desc:"Subscript",
    code_desc:"HTML bron bewerken",
    cleanup_desc:"Code opruimen",
    image_desc:"Afbeelding invoegen/bewerken",
    unlink_desc:"Link verwijderen",
    link_desc:"Link invoegen/bewerken",
    linkfollow_desc:"Link volgen",
    redo_desc:"Herhalen (Ctrl+Y)",
    undo_desc:"Ongedaan maken (Ctrl+Z)",
    indent_desc:"Inspringing vergroten",
    outdent_desc:"Inspringing verkleinen",
    numlist_desc:"Nummering",
    bullist_desc:"Opsommingstekens",
    justifyfull_desc:"Uitvullen",
    justifyright_desc:"Rechts uitlijnen",
    justifycenter_desc:"Centreren",
    justifyleft_desc:"Links uitlijnen",
    striketrough_desc:"Doorhalen",
    anchor_delta_height:"",
    anchor_delta_width:"",
    charmap_delta_height:"",
    charmap_delta_width:"",
    colorpicker_delta_height:"",
    colorpicker_delta_width:"",
    link_delta_height:"",
    link_delta_width:"",
    image_delta_height:"",
    image_delta_width:"",
    
    paste_label : "Plakken",
    anchor_label : "Anker",
    image_label : "Afbeelding",
    hr_label : "Horizontale lijn",  
    charmap_label : "Symbool",
    link_label : "Link",
    unlink_label : "Verwijder link",

    paragraph_label : "Standaard",
    paragraph_desc : "Standaard",

    h1_label : "Kop 1",
    h2_label : "Kop 2",
    h3_label : "Kop 3",
    h4_label : "Kop 4",
    h5_label : "Kop 5",
    h6_label : "Kop 6",

    cleanup_label : "Code opruimen",
    removeformat_label : "Opmaak verwijderen",
    
     Insert : 'Invoegen',
     Source : 'Broncode',
     Image  : 'Afbeelding'
    
});